// In-memory course data store
// Structured so a database can replace this later

export interface Resource {
  id: string;
  courseId: string;
  type: 'pdf' | 'notes' | 'question-bank' | 'topics' | 'lecture';
  title: string;
  content: string; // extracted text content
  fileName?: string;
  contributorName?: string;
  contributorUrl?: string;
  createdAt: string;
}

export interface Course {
  id: string;
  name: string;
  description: string;
  resources: Resource[];
}

// In-memory store
const courses: Course[] = [
  {
    id: 'os-101',
    name: 'Operating Systems',
    description: 'Fundamentals of Operating Systems',
    resources: [
      {
        id: 'demo-1',
        courseId: 'os-101',
        type: 'notes',
        title: 'Process Management Notes',
        content: `Process Management in Operating Systems

A process is a program in execution. It includes the program code (text section), current activity (program counter, registers), stack (temporary data like function parameters, return addresses, local variables), data section (global variables), and heap (dynamically allocated memory).

Process States:
1. New: The process is being created
2. Running: Instructions are being executed
3. Waiting: The process is waiting for some event (I/O completion, signal)
4. Ready: The process is waiting to be assigned to a processor
5. Terminated: The process has finished execution

Process Control Block (PCB):
Each process is represented by a PCB containing: Process state, Program counter, CPU registers, CPU scheduling information, Memory management information, Accounting information, I/O status information.

Process Scheduling:
- Long-term scheduler (job scheduler): selects processes from pool and loads them into memory
- Short-term scheduler (CPU scheduler): selects from ready queue and allocates CPU
- Medium-term scheduler: swaps processes in and out of memory

Context Switch:
When CPU switches from one process to another, the system must save the state of the old process and load the saved state for the new process. Context switch time is overhead - the system does no useful work while switching. Time depends on hardware support.

Process Creation:
- Parent process creates children processes using fork() system call
- Child gets a copy of parent's address space
- exec() system call replaces the process memory space with a new program
- Parent can wait() for child to terminate

Inter-Process Communication (IPC):
1. Shared Memory: A region of memory shared between processes. Faster, but requires synchronization.
2. Message Passing: Processes communicate through send() and receive() operations. Easier to implement but slower due to system call overhead.

Threads:
A thread is a basic unit of CPU utilization comprising a thread ID, program counter, register set, and stack. Threads share code section, data section, and OS resources with other threads of the same process.

Benefits of multithreading:
- Responsiveness
- Resource sharing
- Economy
- Scalability`,
        createdAt: '2024-01-15T10:00:00Z',
      },
      {
        id: 'demo-2',
        courseId: 'os-101',
        type: 'notes',
        title: 'Memory Management Notes',
        content: `Memory Management in Operating Systems

Memory management is the functionality of an operating system which handles and manages primary memory. It keeps track of each byte in memory, whether allocated or free.

Logical vs Physical Address Space:
- Logical address: generated by CPU, also called virtual address
- Physical address: address seen by the memory unit (loaded into memory address register)
- Mapping from logical to physical is done by Memory Management Unit (MMU)

Contiguous Memory Allocation:
- Each process is contained in a single contiguous section of memory
- Memory is divided into partitions
- Fixed partitioning: memory divided into fixed-size partitions. Causes internal fragmentation.
- Variable partitioning: OS keeps a table of available memory. Causes external fragmentation.

Allocation Strategies:
1. First Fit: Allocate the first hole that is big enough
2. Best Fit: Allocate the smallest hole that is big enough (must search entire list)
3. Worst Fit: Allocate the largest hole (must also search entire list)

Paging:
- Physical memory is divided into fixed-size blocks called frames
- Logical memory is divided into same-size blocks called pages
- Page table maps logical pages to physical frames
- No external fragmentation, but internal fragmentation possible
- Page size is typically 4KB

Page Table Implementation:
- Page table is kept in main memory
- Page Table Base Register (PTBR) points to the page table
- Translation Lookaside Buffer (TLB) is a hardware cache for page table entries
- TLB hit avoids memory access for page table lookup

Virtual Memory:
- Allows execution of processes not completely in memory
- Separates logical memory from physical memory
- Implemented through demand paging

Demand Paging:
- Pages loaded into memory only when needed (lazy swapper/pager)
- Valid-invalid bit in page table indicates if page is in memory
- Page fault occurs when accessing a page not in memory

Page Replacement Algorithms:
1. FIFO: Replace the oldest page. Simple but suffers from Belady's anomaly.
2. Optimal: Replace page not used for longest period. Best but impossible to implement.
3. LRU (Least Recently Used): Replace least recently used page. Good approximation of optimal.
4. Clock Algorithm: Approximation of LRU using reference bits.

Thrashing:
- Occurs when a process spends more time paging than executing
- Caused by too many processes competing for too few frames
- Working set model helps prevent thrashing`,
        createdAt: '2024-01-16T10:00:00Z',
      },
      {
        id: 'demo-3',
        courseId: 'os-101',
        type: 'question-bank',
        title: 'OS Exam Questions',
        content: `Operating Systems Important Questions

1. Explain the different states of a process with a state transition diagram.
2. What is a Process Control Block? Describe its components.
3. Differentiate between preemptive and non-preemptive scheduling.
4. Explain the concept of context switching. Why is it considered overhead?
5. Compare and contrast shared memory and message passing IPC mechanisms.
6. What are threads? Explain the benefits of multithreading.
7. Explain paging and how it eliminates external fragmentation.
8. What is a TLB? How does it improve memory access time?
9. Explain demand paging and the steps involved in handling a page fault.
10. Compare FIFO, Optimal, and LRU page replacement algorithms.
11. What is thrashing? How can it be prevented using the working set model?
12. Explain the difference between logical and physical addresses.
13. Compare First Fit, Best Fit, and Worst Fit memory allocation strategies.
14. What is virtual memory? Explain its advantages.
15. Describe the role of the Memory Management Unit (MMU).`,
        createdAt: '2024-01-17T10:00:00Z',
      },
    ],
  },
  {
    id: 'dbms-101',
    name: 'Database Management Systems',
    description: 'Introduction to DBMS concepts',
    resources: [],
  },
  {
    id: 'cn-101',
    name: 'Computer Networks',
    description: 'Networking fundamentals',
    resources: [],
  },
];

export function getAllCourses(): Course[] {
  return courses.map(c => ({ ...c, resources: [...c.resources] }));
}

export function getCourse(id: string): Course | undefined {
  const course = courses.find(c => c.id === id);
  if (!course) return undefined;
  return { ...course, resources: [...course.resources] };
}

export function getCourseResources(courseId: string): Resource[] {
  const course = courses.find(c => c.id === courseId);
  return course ? [...course.resources] : [];
}

export function getCombinedResourceText(courseId: string): string {
  const resources = getCourseResources(courseId);
  return resources.map(r => `--- ${r.title} (${r.type}) ---\n${r.content}`).join('\n\n');
}

export function addResource(resource: Omit<Resource, 'id' | 'createdAt'>): Resource {
  const newResource: Resource = {
    ...resource,
    id: `res-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    createdAt: new Date().toISOString(),
  };
  const course = courses.find(c => c.id === resource.courseId);
  if (course) {
    course.resources.push(newResource);
  }
  return newResource;
}

export function addCourse(name: string, description: string): Course {
  const newCourse: Course = {
    id: `course-${Date.now()}`,
    name,
    description,
    resources: [],
  };
  courses.push(newCourse);
  return newCourse;
}
